### ISSUE TITLE
How to use the handle_func?  is there some examples

### ISSUE THREAD

**Issue by LiZhangMing** [yym6472/back_translate#1]
def back_translate(text: str,
                   schemas: Dict[str, List[List[str]]],
                   keywords: List[str] = None,
                   handle_func: Callable[[Dict[str, str]], Any] = lambda x: x) -> Any:

How to use the handle_func?  is there some examples

**Comment by yym6472** [comment]
handle_func是一个处理返回结果的函数。back_translate默认的返回结果是一个Dict，对于schema中的每一项（作为key）都会有一条翻译结果（作为value）。如果提供了handle_func，那么会使用该函数对结果进行处理，然后再返回。比如我想只取所有对回译结果，去重后转换为一个List，就可以定义如下的函数：
```python
def handle_res(res):
    no_repeat = list(set(res.values()))
    return no_repeat
```
调用`result = back_translate(text, schemas, keywords, handle_func=handle_res)`就等价于`result = handle_res(back_translate(text, schemas, keywords))`。
