### ISSUE TITLE
Is there a limit to the number of translations per day?

### ISSUE THREAD

**Issue by LiZhangMing** [yym6472/back_translate#2]
Is there a limit to the number of translations per day?

**Comment by yym6472** [comment]
这个repo基于非官方的翻译API，所以应该没有每日调用量的限制（至少我此前在用的过程中没有遇到过），但非官方的翻译API会有调用频次的限制，所以不能调用太快（否则会封IP），这个我在代码了通过time.sleep去控制了。

**Comment by LiZhangMing** [comment]
多谢  兄弟 。还有个问题麻烦您看下 就是那个函数的使用

**Comment by LiZhangMing** [comment]
在back_translate.py  中  def back_translate 这个方法中的handle_func参数如何写呢

**Comment by yym6472** [comment]
> 在back_translate.py 中 def back_translate 这个方法中的handle_func参数如何写呢

没有特殊要求的话留空就可以了

**Comment by LiZhangMing** [comment]
keywords.text  这个文件需要我先去调研下 我想翻译的文章主要的关键词吗？

**Comment by yym6472** [comment]
对，主要就是那些不希望在回译过程中被破坏的专有名词。

**Comment by LiZhangMing** [comment]
太棒了 多谢
